### PR TITLE
Add files for Jira ticket C4G-74 scan results

### PR DESCRIPTION
**Pull request by Winerip**
- [X] Jira ticket number [C4G-74](https://jira.sdlc.redcross.us/browse/C4G-74)
- [x] Created file results_`TicketNumber`_`ToolAbbreviation`in `/public/scan-results/data`

### Issues with some links 
- [ ] Skip some URL due an Error (List Included)
- [ ] Set Label `Missing_URL` for future reference

### CODE REVIEW

**Comment by bhaumikmistry** [comment]
Thank you. Looks good.

**Comment by Winerip** [comment]
I just realized, my initial comments apparently got lost. I basically created this with the auto-lighthouse script only, I haven't actually manually looked at every page. Are there issues I need to look out for beyond what the script does? I saw mentions of issues with pages that redirect elsewhere, but the lighthouse command will happily analyze a page that redirects. Mainly want to confirm my process is okay before repeating it on a bunch of other tasks, since this seemed easy with the script (once I figured out how to modify and run it).

**Comment by bhaumikmistry** [comment]
> I just realized, my initial comments apparently got lost. I basically created this with the auto-lighthouse script only, I haven't actually manually looked at every page. Are there issues I need to look out for beyond what the script does? I saw mentions of issues with pages that redirect elsewhere, but the lighthouse command will happily analyze a page that redirects. Mainly want to confirm my process is okay before repeating it on a bunch of other tasks, since this seemed easy with the script (once I figured out how to modify and run it).

Do not merge yet. We will discuss this issue very soon.

**Comment by Winerip** [comment]
This one is a bit old, and because I created it from my master (this was my first PR) I'll do this task over in a fresh branch. Keeping my master in this state is causing me a little trouble.

**Pull request closed without merging**
