### PR TITLE
C4g 147 reports

### PR DESCRIPTION
**Pull request by rousik**
- [x] Jira ticket number [#147](https://jira.sdlc.redcross.us/browse/C4G-147)
- [x] Created file results `C4G_147_CD` in `/public/scan-results/data`

### Issues with some links 
- [x] Skip some URL due an Error (row 24 doesn't have valid URL)
- [ ] Set Label `Missing_URL` for future reference

XML file only contains 38 rows.
Report generated on Linux using `auto-lighthouse`, reusing chrome instance for the entire batch.

### CODE REVIEW

**Comment by Winerip** [comment]
It looks like Row 24 is intended to be https://www.redcrossblood.org/local-homepage/location/-bloomington--il-blood-donation-center.html and the leading - caused a bug with the normal assembly process for the final URL, as excel read it as a bad reference. I encountered this once before, it should be possible to run the audit on the correct URL though.

**Comment by bhaumikmistry** [comment]
> It looks like Row 24 is intended to be https://www.redcrossblood.org/local-homepage/location/-bloomington--il-blood-donation-center.html and the leading - caused a bug with the normal assembly process for the final URL, as excel read it as a bad reference. I encountered this once before, it should be possible to run the audit on the correct URL though.

@Winerip is it ready to merge?

**Comment by Winerip** [comment]
> > It looks like Row 24 is intended to be https://www.redcrossblood.org/local-homepage/location/-bloomington--il-blood-donation-center.html and the leading - caused a bug with the normal assembly process for the final URL, as excel read it as a bad reference. I encountered this once before, it should be possible to run the audit on the correct URL though.
> 
> @Winerip is it ready to merge?

Looking at the files, it looks like the files (except 24) after 21 are all a single line change? Also, file 0 is just a single line. That doesn't seem right.

**Comment by rousik** [comment]
Good catch. It seems that when the automation broke on the invalid script, the resulting json reports were created empty. Let me fix this.

**Comment by rousik** [comment]
Note to self/others: maybe we could add the verification of json files into presubmit check or PR check.

**Comment by rousik** [comment]
Note that the invalid bloomington url does not exist anyways.

**Comment by rousik** [comment]
Reports have been regenerated. Indexing is now 0-based and I have uploaded reports generated without `--headless` option (as that affects performance audits).

**Comment by rousik** [comment]
This should be ready to merge.

**Pull request merged**
