### PR TITLE
Move c4g-19 scan results to public/scan-results

### PR DESCRIPTION
**Pull request by MichaelTamaki**
Moves C4G-19 scan results to public/scan-results folder.

- [ ] Created folder name with result_`TicketNumber` 
- [ ] Created file results_`TicketNumber`_`ToolAbbreviation`
- [ ] Added Json Results from your scan
- [ ] Others (Details below)

### CODE REVIEW

**Comment by bhaumikmistry** [comment]
@annahinnyc He needs to move the files from individual folder to this universal folder?

**Comment by bhaumikmistry** [comment]
@MichaelTamaki You might have to change the location of the file created.

**Comment by annahinnyc** [comment]
Hi, Michael! Thanks for sending this in. We've modified the workflow today in the ReadMe to simplify things.  Would you please be able to move your scan results to the main "data" folder now?

**Comment by MichaelTamaki** [comment]
Looks like the c4g-19 scan results were moved into the correct folder already! Will close this.

**Pull request closed without merging**
