### PR TITLE
Move legacy manual audits into legacy-audits/ directory.

### PR DESCRIPTION
**Pull request by rousik**
Eventually we might consider deleting those entirely

This should probably be merged only after https://github.com/annahinnyc/code4good-accessibility/pull/150 to ensure it does not mix up with the dashboard code.

### CODE REVIEW

**Comment by Winerip** [comment]
It looks like this breaks the presubmit checks - do we want to update that check for the new location? And remove it altogether since we're no longer uploading manual audits?

**Comment by rousik** [comment]
I think that the presubmit check no longer makes sense and we should drop it. @bhaumikmistry what do you think?

**Comment by bhaumikmistry** [comment]
If there is a change in work flow Yes, we should create a PR before this to disable/remove it.

**Comment by rousik** [comment]
I think we can ignore presubmit failure for this one as the manual audits are not used by the dashboard anyways.

**Comment by rousik** [comment]
Could you take care of it?

**Pull request merged**
