### PR TITLE
C4G-28 Audits(49 urls).

### PR DESCRIPTION
**Pull request by Padmavathy25**
- [x] Jira ticket number [#number](link)
- [ ] Created file results_`TicketNumber`_`ToolAbbreviation`in `/public/scan-results/data`

### Issues with some links 
- [ ] Skip some URL due an Error (List Included)
- [ ] Set Label `Missing_URL` for future reference

### CODE REVIEW

**Comment by bhaumikmistry** [comment]
@MichaelTamaki Why only 49 files??

**Comment by bhaumikmistry** [comment]
Thank you for your contribution!! Did you check if you are not missing a url audit?

**Comment by Padmavathy25** [comment]
I named the json files from C4G-28_CD_2.json to C4G-28_CD_50.json. (As the url in excel file starts from second row).

**Comment by Padmavathy25** [comment]
I m creating a new PR

**Pull request closed without merging**
