### PR TITLE
C4G-62 Audit files

### PR DESCRIPTION
**Pull request by Padmavathy25**
- [X] Jira ticket number [#C4G-62](https://jira.sdlc.redcross.us/browse/C4G-62)
- [x] Created file results_`TicketNumber`_`ToolAbbreviation`in `/public/scan-results/data`

### Issues with some links 
- [ ] Skip some URL due an Error (List Included)
- [ ] Set Label `Missing_URL` for future reference

### CODE REVIEW

**Comment by bhaumikmistry** [comment]
Thank you so much for your contribution!! 


Please edit the Pr description with Jira ticket number and the link

**Comment by Padmavathy25** [comment]
Made the changes. Thank you.

**Comment by bhaumikmistry** [comment]
The file location is incorrect. Please move all the files to DATA DIRECTORY. Thank you.

**Comment by Padmavathy25** [comment]
Sorry about that. Let me change the directory.

**Pull request closed without merging**
